using LeedCodeProblems.Problems;
using System;

TwoSum.TestTwoSum();
Console.WriteLine("Two Sum - Ok");
Palindrome.TestIsPalindrome();
Console.WriteLine("Palindrome - Ok");
PalindromeAlt.TestIsPalindrome();
Console.WriteLine("Palindrome Alt - Ok");
RomanToInteger.TestRomanToInteger();
Console.WriteLine("Roman To Integer - Ok");
LongestCommonPrefix.TestLongestCommonPrefix();
Console.WriteLine("Longest Common Prefix - Ok");
ValidParentheses.TestValidParentheses();
Console.WriteLine("Valid Parentheses - Ok");
MergeTwoSortedLists.TestMergeTwoLists();
Console.WriteLine("Merge Two Sorted Lists - Ok");
MargeTwoSortedListsAlt.TestMergeTwoLists();
Console.WriteLine("Merge Two Sorted Lists Alt - Ok");
Console.ReadLine();
